### ISSUE TITLE
Audio input quality seems bad

### ISSUE THREAD

**Issue by brainvine** [twilio-samples/speech-assistant-openai-realtime-api-node#13] opened 2024-10-08 07:38 UTC
I've noticed that the audio input quality is quite poor, which results in the AI struggling to understand what's being said. When using the transcribe function from OpenAI, I observe numerous transcription errors. These issues don't occur in the OpenAI Playground that often. 

The errorrate is so high I don't think I can put this live, especially considering people are often not that clear as I am within the testing environment. 

**Possible Cause:**

I suspect this might be related to the audio input format (g711_ulaw). The Playground uses PCM16, which seems to offer much better quality. However, the difference in transcription quality shouldn't be this significant, regardless of the format used I hope?

Request:

Could it be possible to review or adjust the audio input format to PCM16, or investigate why there's such a significant difference in transcription quality between the current implementation and the Playground?

Is there a way to increase input quality somehow?

**Comment by badereddineqodia** [comment] 2024-10-08 09:43
I totally agree with you @brainvine. I've noticed the same issue, especially when dealing with local dialects. While he can somewhat handle English (not Good), it struggles significantly with dialects like Darija or other regional languages. The difference in transcription accuracy between the current implementation and the OpenAI Playground is very noticeable.

**Comment by badereddineqodia** [comment] 2024-10-10 09:15
@pkamp3 Do you have any ideas? Can we work with PCM16 rather than G.711 u-law?

**Comment by kjjd84** [comment] 2024-10-12 09:03
same issue here

also the ai voice is crackling a little bit now

**Comment by alfiesal** [comment] 2024-10-14 07:17
Does this work for anyone? I can't achieve the same results as in the tutorial. Somehow, the audio quality is poor, which makes the Agent not understand what I'm saying. When I use direct integration with RealtimeAPI, everything works perfectly.

**Comment by badereddineqodia** [comment] 2024-10-16 16:18
I don't fully understand what the issue is, as the problem doesn't seem clearly defined. Is the problem related to Twilio or OpenAI? I used Twilio with Azure's Speech-to-Text, and it worked quite well. However, when using Twilio with OpenAI, the results seem poor.

I suspect there may be an issue with the audio encoding between Twilio and OpenAI. Twilio might not be supporting OpenAI's default audio encoding format, or OpenAI may need to add broader support for more formats. Currently, we have to perform a transformation in between: we receive the audio data from Twilio, transform it, and then send it to OpenAI.

**Comment by pkamp3** [comment] 2024-10-16 19:47
Hey all, I hear your concerns but we're limited by the channel and this is out of scope for this repo. G.711 A-law or u-law are what we need to use for calls on the PSTN, and [that's what Media Streams supports](https://www.twilio.com/docs/voice/media-streams/websocket-messages#start-message).

Let me point you at a few ideas, though:
- You might be able to make the conversion better yourself. As I'm writing this, [OpenAI wants PCM16 24 kHz little-endian](https://platform.openai.com/docs/guides/realtime/concepts) if you make the conversion with some optimizations, filters, or your other ideas.
- Our [Voice client supports OPUS](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice), might work better for you – but it depends on whether your call crosses the PSTN. In this case, you'd still need to transcode before sending audio between the two WebSockets. My colleague Michael Carpenter [wrote a bit about considerations here](https://www.twilio.com/en-us/blog/how-i-learned-to-stop-worrying-and-use-the-pstn).

**Closed by pkamp3** 2024-10-16 19:47 UTC

**Comment by jazzytomato** [comment] 2025-01-05 22:17
I am having the same problem. 

I've been trying to debug this and so I've made 100s of recordings to test openAI understanding of my voice based on different audio quality. I'm testing OpenAI understanding of dates, numbers etc... for which I get very poor result via Twilio.

**It turns out that I get very accurate results when I play those recordings with downgraded quality directly to OpenAI (bypassing Twilio).**. Twilio reports good stats on the phone calls (no packet loss or jitter etc)

I am trying to mimic what I think I'm getting from Twilio by converting raw audio with commands like this:
```sh
sox recording_input.wav \
	-r 8000 \
	-c 1 \
	-b 8 \
	-e mu-law \
	phone_quality.wav \
	gain -10 \
	highpass 300 \
	lowpass  3400
```

Even with much lower gain and tighter highpass / lowpass, I'm getting accurate results from OpenAI.

I send the audio recording to OpenAI using the payload below, rather than `input_audio_buffer.append`:

```json
{
  "type": "conversation.item.create",
  "item": {
    "type": "message",
    "role": "user",
    "content": [
      {
        "type": "input_audio",
        "audio": "b64 encoded file"
      }
    ]
  }
}
```
